export const LOAD_MORE_CONTACTS_SUCCESS = "LOAD_MORE_CONTACTS_SUCCESS";
export const SORT_ONLY_EVEN_CONTACT_IDS = "SORT_ONLY_EVEN_CONTACT_IDS";
export const FILTER_CONTACTS_SUCCESS = "FILTER_CONTACTS_SUCCESS";
